spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: player-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/player/**
        - id: auth-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/auth/**
server:
  port: 8000